baseURL = 'https://lucaslimafernandes.github.io/'
languageCode = 'pt-br'
title = 'Aprendendo AWS com LocalStack'
baseURL = 'https://lucaslimafernandes.github.io/aprendendo-aws/'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  showReadingTime = true

[menu]
  [[menu.main]]
    name = "Sobre"
    url = "/sobre/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
